spring.application.name=basketservice
server.port=0

#Eureka Config
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.client.service-url.defaultZone=http://localhost:8090/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${instanceId:${random.value}}

sprin.data.redis.host=localhost
spring.data.redis.port=6379

spring.cloud.stream.kafka.binder.brokers=localhost:29092
spring.cloud.stream.bindings.basketClear-in-0.destination=basket-clear-event
spring.cloud.stream.bindings.basketClear-in-0.group=basket-service
spring.cloud.function.definition=basketClear;

jwt.secret.key=+VWtE5JIlbXqSd6NuR5mklPGX1fTxWRdLDvwm8MNeJU=

jwt.expiration=3600000


