spring.application.name=salesservice
server.port=0
#Eureka Configuration

eureka.client.fetch-registry=true
eureka.client.register-with-eureka = true
eureka.client.service-url.defaultZone= http://localhost:8090/eureka
# Eurekaya kay?t olurken hostname yerine Ip adresini kullan?r
eureka.instance.prefer-ip-address= true
eureka.instance.instance-id= ${spring.application.name}:${instanceId:${random.value}}

spring.data.mongodb.database=salesservicedb
spring.data.mongodb.port=27017
spring.data.mongodb.uri=mongodb://localhost:27017

jwt.secret.key=+VWtE5JIlbXqSd6NuR5mklPGX1fTxWRdLDvwm8MNeJU=

jwt.expiration=3600000
